### ISSUE TITLE
Bug for my FiveM server.

### ISSUE THREAD

**Issue by BradyMarcade** [eblio/3dme#6]
Hey, man I don’t know how to get in touch with you? Your last update for 3D me won’t work in my server anymore. Is their anyway I could get the 2 to lasted version?

**Comment by eblio** [comment]
Hi, I'm currently working on fixing that, I'm sorry about the inconvenience. You can get the previous versions here : https://forum.cfx.re/t/release-me-but-the-text-is-3d-printed/149691.

**Comment by eblio** [comment]
I pussed a fix, but couldn't test it with multiple players yet. Feel free to give feedback about this one.
