### ISSUE TITLE
/do and custom

### ISSUE THREAD

**Issue by ZROMO** [eblio/3dme#7]
Will it have /do and maybe even custom trigger?

Custom, I mean like, triggered by an event or export, with preset text, like "/me drawing an weapon", so it could be set everytime ped draws a gun or any other automatic commands who has them. :)

**Comment by BlueSky-fur** [comment]
This is not an issue.

**Comment by eblio** [comment]
You can already trigger the 3D text using an event on the server. Custom trigger isn't a planned feature.
